FORCE:

test_email:
    #python Generation_notes_d_auteur.py -i "Auteurs_Dkh_Gen_19_06_2020 - Feuille 2.tsv" -o auteurs_dkh_19_06_2020 -email

auteurs_dkh_19_06_2020: FORCE
	# python Generation_notes_d_auteur.py -h
	python Generation_notes_d_auteur.py -i "Auteurs_Dkh_Gen_19_06_2020 - Feuille 1.tsv" -o auteurs_dkh_19_06_2020

