

whisper_sept2020:
	python extract_sales.py -steam-only -i config.china.sept2020.json > china.sept2020.txt
	python extract_sales.py -steam-only -i config.taiwan.sept2020.json > taiwan.sept2020.txt
	python extract_sales.py -steam-only -i config.hk.sept2020.json > hk.sept2020.txt